In [ ]:
! pip install numpy pandas matplotlib seaborn scipy

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
x = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
x

   A  B
0  1  4
1  2  5
2  3  6

In [7]:
np.mean([0,1,2,3,4,5,6,7,8,9])

np.float64(4.5)

In [8]:
airbnb = pd.read_csv('./data/airbnb_hw.csv')
airbnb.head()

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0

In [ ]:
airbnb.columns = airbnb.columns.str.strip()

airbnb['Price'] = pd.to_numeric(airbnb['Price'], errors='coerce')

airbnb.groupby('Neighbourhood')['Price'].mean().sort_values(
    ascending=False
).head(10)

KeyError: 'Neighbourhood'